# use java support.
language: java
jdk:
  - oraclejdk8

# install the newest java.
addons:
  apt:
    packages:
      - oracle-java8-installer

# use operating systems.
os:
  - linux

# run in container und keep gradle cache.
sudo: false
cache:
  directories:
    - $HOME/.gradle

# setup jobs.
env:
  - USE_FRAMEBUFFER=true
  - USE_FRAMEBUFFER=false _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"

# allow job to fail without framebuffer
matrix:
  allow_failures:
  - env: USE_FRAMEBUFFER=false _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"

# run on xvfb screen.
before_install:
  - if [ $USE_FRAMEBUFFER = "true" ]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start; fi

# skip install stage.
install: true

# run gradle build.
script:
  - ./gradlew build --info
