language: java

sudo: false

env:
  global:
  - secure: XxAYzDEO8Vga/0KfvrMgm4d7VkOky2uHCeJvVR4vMBrMd7bpLE8AtT6Qy99NI/FQdbFu60AAyGJjiXoAZ9gqCvrt8fKGz8vyuyvYlQFVruw0UJ9UPCPazUaE5s/85vuwv7fW2asKlc3ZPHskWqUpzMUi/rSt5rjfB0Had5arbSo=

before_script:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then export DISPLAY=:99.0 && /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16; fi

before_install: .ci/before_install.sh

install: true

script: .ci/script.sh

after_success: .ci/after_success.sh

jobs:
  fast_finish: true
  allow_failures:
    - os: linux
      env:
        - TRAVIS_JAVA_VERSION="10"
        - _JAVA_OPTIONS="--add-opens=java.base/java.util=ALL-UNNAMED --add-exports=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED -Dprism.verbose=true"
  include:
    - stage: lint
      os: linux
      dist: trusty
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - oracle-java8-installer
      script: ./gradlew checkstyleMain checkstyleTest license spotbugsMain spotbugsTest :testfx-spock:codenarcMain :testfx-spock:codenarcTest
    - stage: test
     # Ubuntu Linux (trusty) / Oracle JDK 8 / Headed
      os: linux
      dist: trusty
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - oracle-java8-installer
    # Ubuntu Linux (trusty) / Oracle JDK 8 / Headless
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      env:
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dprism.verbose=true"
      addons:
        apt:
          packages:
            - oracle-java8-installer
            - gdb
    # Ubuntu Linux (trusty) / Oracle JDK 10 / Headed
    - os: linux
      dist: trusty
      install: . ./install-jdk.sh -F 10 -L BCL
      env:
        - TRAVIS_JAVA_VERSION="10"
        - _JAVA_OPTIONS="--add-opens=java.base/java.util=ALL-UNNAMED --add-exports=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED -Dprism.verbose=true"
      addons:
        apt:
          packages:
            - gdb
    # Ubuntu Linux (trusty) / Oracle JDK 10 / Headless
    - os: linux
      dist: trusty
      install: . ./install-jdk.sh -F 10 -L BCL
      env:
        - _JAVA_OPTIONS="--add-opens=java.base/java.util=ALL-UNNAMED --add-exports=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.verbose=true"
      addons:
        apt:
          packages:
            - gdb
    # Ubuntu Linux (trusty) / Oracle JDK 10 / Headed / HiDPI
    - os: linux
      dist: trusty
      install: . ./install-jdk.sh -F 10 -L BCL
      env:
        - _JAVA_OPTIONS="--add-opens=java.base/java.util=ALL-UNNAMED --add-exports=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED -Djdk.gtk.verbose=true -Djdk.gtk.version=3 -Dglass.gtk.uiScale=2.0 -Dprism.verbose=true"
      addons:
        apt:
          packages:
            - gdb
    # macOS / Oracle JDK 8 / Headless
    - os: osx
      osx_image: xcode9.3
      env:
        - TRAVIS_JAVA_VERSION="8"
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dprism.verbose=true"
     # macOS / Oracle JDK 10 / Headless
    - os: osx
      osx_image: xcode9.3
      env:
        - TRAVIS_JAVA_VERSION="10"
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.verbose=true"
    # It is not currently possible to run JavaFX in headed mode on macOS on Travis CI
    # with the OpenGL ES graphics pipeline. While it is possible to run with "-Dprism.order=sw"
    # this "partial headless" testing scenario does not provide useful information.
    - stage: deploy
      before_install: true
      script: true
      after_success: true
      script: .ci/deploy.sh
      os: osx
      osx_image: xcode9
      env:
        - secure: "McAqe7fSHacgoaf6EN2xsJtQl+7bHWJFaxt9KjLsX5An/LEqCOCVAgRQA7pVpoc3VQUw3Lq997aDGK4NyRco6SmKb+73/L6AF14W9KO7ItNX4HVq16JDEkTqlfDip+/1Jo/Z8UDoQ2J9/2HViZ4ZoZDdEP9CjGJGlfEyUaEnAQQ="
        - secure: "YzaXTwRHng74Uegz0COmH2/U6PZ4VghDeoXFog5Eds2ZSuUGG9NXBQTdCcBgTwA9KPmu1fvKhk4HqJeru4fpD3NqZ+Ks3znvXOPXgydr3SxgJUvWCJkRQljXOE5BlI07R1qVnDWwTqSDyt64ffaJo3XT0+3uOwnauJrMqexsniM="
        - secure: "eSQaOxDMfLW3V1cxtKcm0i/BesSrRw1bTi01fAjTR6RxsXP00YAylNgYBgoGRrED16kM5FkQzOf75CDCw6l7CanXky/A7quD0IMo0pkwX/q5OJWIK7NAGnV4DekDnYW0yrMTxuygR0ALMkgwT5S+CP3/1aY6BNO11LNSHgQUXiM="
        - secure: "BXTn0eNI4ueday8ZMC4KPnbJxWy7HADRUc5pjLMC70W9j2P6T5P18zUYwXHFnRdNxAEPa3rkjCLXx3XyMezhm5twkHpUt/Hyb0kgN0CYzEm0fad23Dayn7HVdGlKh6WQnjC/VQ54k/MCHEk4F0W8ip7RrG1FpTfhpWAa3j1Tq00="
      if: tag =~ ^v[0-9]+.[0-9]+.[0-9]+(-alpha|-beta)?$

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2532276e31bee9ba82b7
    on_success: change
    on_failure: always
