# use java support.
language: java
jdk:
  - oraclejdk8

# run in container und keep gradle cache.
sudo: false
cache:
  directories:
    - $HOME/.gradle

# run on xvfb screen.
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# skip install stage.
install: true

# run gradle build.
script: ./gradlew build
