language: java
sudo: false

addons:
  apt:
    packages:
      - gdb
      - oracle-java8-installer
      - oracle-java9-installer

# keep gradle cache.
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      env: USE_FRAMEBUFFER=true
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      env:
        - USE_FRAMEBUFFER=false
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
    - os: linux
      dist: trusty
      jdk: oraclejdk9
      env:
        - USE_FRAMEBUFFER=true
        - _JAVA_OPTIONS="-XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED --add-exports-private java.base/java.util=ALL-UNNAMED --add-exports=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED --permit-illegal-access"
    - os: osx
      osx_image: xcode8.2
      env:
        - OSX_HEADLESS=false
        - _JAVA_OPTIONS="-Dprism.order=sw"
    - os: osx
      osx_image: xcode8.2
      env: _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
  allow_failures:
    - jdk: oraclejdk9
    - env:
      - USE_FRAMEBUFFER=false
      - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
    - env:
      - OSX_HEADLESS=false
      - _JAVA_OPTIONS="-Dprism.order=sw"


before_script:
  - echo $HOME
  - echo $JAVA_OPTS
  - echo $GRADLE_OPTS
  # run on xvfb screen (for linux).
  - if [ $USE_FRAMEBUFFER = "true" ]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start; fi

  # run on xvfb screen using sudo (for OSX)
  - if [ $_JAVA_OPTIONS="-Dprism.order=sw" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )& fi

before_install: .ci/before_install.sh

# skip install stage.
install: true

# run gradle build.
script: .ci/script.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2532276e31bee9ba82b7
    on_success: change
    on_failure: always

