version: "{branch} {build}"

environment:
  matrix:
    # Java 8 / AWT Robot
    - JAVA_VERSION: "8"
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0
      _JAVA_OPTIONS: "-Dtestfx.robot=awt"

    # Java 8 / Glass Robot (deadlock?)
    # - JAVA_VERSION: "8"
    #   JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    #  _JAVA_OPTIONS: "-Dprism.verbose=true -Dtestfx.robot=glass"

    # Java 8 / AWT Robot / HiDPI
    - JAVA_VERSION: "8"
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0
      _JAVA_OPTIONS: "-Dtestfx.robot=awt -Dtestfx.awt.scale=true -Dglass.win.uiScale=200%"

    # Java 8 / Glass Robot / HiDPI (deadlock?)
    # - JAVA_VERSION: "8"
    #   JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    #  _JAVA_OPTIONS: "-Dprism.verbose=true -Dtestfx.robot=glass -Dglass.win.uiScale=200%"

    # Java 8 / Headless
    - JAVA_VERSION: "8"
      _JAVA_OPTIONS: "-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k"
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0

    # Java 11 / AWT Robot
    - JAVA_VERSION: "11"
      JAVA_HOME: C:\jdk11
      _JAVA_OPTIONS: "-Dtestfx.robot=awt"

    # Java 11 / Glass Robot (deadlock?)
    # - JAVA_VERSION: "11"
    #  JAVA_HOME: C:\jdk11
    #  _JAVA_OPTIONS: "-Dtestfx.robot=glass"

    # Java 11 / AWT Robot / HiDPI
    - JAVA_VERSION: "11"
      JAVA_HOME: C:\jdk11
      _JAVA_OPTIONS: "-Dtestfx.robot=awt -Dtestfx.awt.scale=true -Dglass.win.uiScale=200%"

    # Java 11 / Headless (fails because of JDK-8201539)
    - JAVA_VERSION: "11"
      JAVA_HOME: C:\jdk11
      _JAVA_OPTIONS: "-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw"

matrix:
  allow_failures:
    - JAVA_VERSION: "11"
      _JAVA_OPTIONS: "-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw"

shallow_clone: true

build:
  verbosity: detailed

build_script:
  - ps: |
      if ($env:JAVA_VERSION -eq "11") {
        $client = New-Object net.webclient
        $client.DownloadFile('http://jdk.java.net/11/', 'C:\Users\appveyor\openjdk11.html')
        $openJdk11 = cat C:\Users\appveyor\openjdk11.html | where { $_ -match "href.*https://download.java.net.*jdk11.*windows-x64.*zip\`"" } | %{ $_ -replace "^.*https:", "https:" } | %{ $_ -replace ".zip\`".*$", ".zip" }
        echo "Download boot JDK from: $openJdk11"
        $client.DownloadFile($openJdk11, 'C:\Users\appveyor\openjdk11.zip')
        Expand-Archive -Path 'C:\Users\appveyor\openjdk11.zip' -DestinationPath 'C:\Users\appveyor\openjdk11'
        Copy-Item -Path 'C:\Users\appveyor\openjdk11\*\' -Destination 'C:\jdk11' -Recurse -Force
      }
      elseif ($env:JAVA_VERSION -eq "10") {
        choco install jdk10 --version 10.0.2 --force --cache 'C:\ProgramData\chocolatey\cache' -params 'installdir=c:\\jdk10'
      }
      refreshenv

  - cmd: |
      java -version
      gradlew --version --no-daemon
      gradlew versions --no-daemon

test_script:
  - gradlew build --no-daemon

on_failure:
  - ps: |
        # Upload any screen captures that may have been grabbed on test failure.
        $screenCaptures = '.\screen_captures\'
        $screenCapturesArchive = 'screen_captures.zip'
        Get-ChildItem -Include @("*.png") -Recurse | Where {$_.Name -match '.*testfx-test\ -\ \d+\.png'} | Copy-Item -Destination (New-Item -Type directory -Force $screenCaptures) -Force
        Compress-Archive -Path $($screenCaptures + '*') -DestinationPath $screenCapturesArchive -CompressionLevel Optimal
        if (Test-Path $screenCapturesArchive) {
          Push-AppveyorArtifact $screenCapturesArchive -Verbose
        }

on_finish:
  - ps: |
        Write-Host 'Uploading test results to AppVeyorâ€¦'
        $wc = New-Object 'System.Net.WebClient'
        ForEach ($file in Get-ChildItem -Recurse -Include "TEST-org.testfx*Test.xml") {
            $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", $file)
        }

cache:
  - C:\Users\appveyor\.gradle\caches
  - C:\Users\appveyor\.gradle\wrapper -> .gradle-wrapper\gradle-wrapper.properties
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\ProgramData\chocolatey\cache -> appveyor.yml

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/2532276e31bee9ba82b7
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
