version: "{branch} {build}"

environment:
  matrix:
    # Java 10 / Headless (fails because of JDK-8201539)
    - JAVA_VERSION: "10"
      JAVA_HOME: C:\jdk10
      _JAVA_OPTIONS: "-Dtestfx.robot=glass -Dprism.order=sw -Dprism.verbose=true -Dprism.debug=true"

matrix:
  allow_failures:
    - JAVA_VERSION: "8"
      _JAVA_OPTIONS: "-Dprism.verbose=true -Dglass.win.uiScale=200%"
    - JAVA_VERSION: "10"
      _JAVA_OPTIONS: "-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.verbose=true -Dprism.debug=true"

shallow_clone: true

build:
  verbosity: detailed

build_script:
  - ps: |
      if ($env:JAVA_VERSION -eq "10") {
        choco install jdk10 --version 10.0.2 --force --cache 'C:\ProgramData\chocolatey\cache' -params 'installdir=c:\\jdk10'
      }
      refreshenv

  - cmd: |
      java -version
      gradlew --version --no-daemon
      gradlew versions --no-daemon

test_script:
  - gradlew build --no-daemon

on_failure:
  - ps: |
        # Upload any screen captures that may have been grabbed on test failure.
        $screenCaptures = '.\screen_captures\'
        $screenCapturesArchive = 'screen_captures.zip'
        Get-ChildItem -Include @("*.png") -Recurse | Where {$_.Name -match '.*testfx-test\ -\ \d+\.png'} | Copy-Item -Destination (New-Item -Type directory -Force $screenCaptures) -Force
        Compress-Archive -Path $($screenCaptures + '*') -DestinationPath $screenCapturesArchive -CompressionLevel Optimal
        Push-AppveyorArtifact $screenCapturesArchive -Verbose

on_finish:
  - ps: |
        Write-Host 'Uploading test results to AppVeyorâ€¦'
        $wc = New-Object 'System.Net.WebClient'
        ForEach ($file in Get-ChildItem -Recurse -Include "TEST-org.testfx*Test.xml") {
            $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", $file)
        }

cache:
  - C:\Users\appveyor\.gradle\caches
  - C:\Users\appveyor\.gradle\wrapper -> .gradle-wrapper\gradle-wrapper.properties
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\ProgramData\chocolatey\cache -> appveyor.yml

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/2532276e31bee9ba82b7
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
